#!/bin/sh

if [ $# -ne 4 ]; then
    echo "Usage: setup-anyfi-optimizer <name> <controller> <port-range> <subnet>"
    exit 1
fi

name=$1
controller=$2
port_range=$3
subnet=$4

# Generate RSA key pair
openssl genrsa -out /tmp/keypair2048.pem 2048

# Load into Vyatta config
alias cfg=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper

cfg begin
cfg set service anyfi optimizer $name controller $controller
cfg set service anyfi optimizer $name port-range $port_range
cfg set service anyfi optimizer $name breakout rsa-key-pair $(grep -v '^-----' /tmp/keypair2048.pem | tr -d '\n')
cfg set service anyfi optimizer $name breakout subnet $subnet
cfg commit
cfg save
cfg end

echo "Public Key (optimizer_key):"
openssl rsa -in /tmp/keypair2048.pem -pubout 2> /dev/null
rm /tmp/keypair2048.pem

exit 0
