#!/bin/sh

FILE=/config/auth/optimizer-key-pair-${RANDOM}.pem
BITS=1024

while getopts b:f:h c
do
  case $c in
    b)       BITS=$OPTARG;;

    f)       FILE=$OPTARG;;

    h)       echo "Usage: vyatta-anyfi-optimizer-keygen [-b bits] [-f file]";
             exit 0;;
  esac
done

echo -n "Generating $BITS bit RSA key pair to file ${FILE}... "
if [ -f $FILE ]; then
    echo "Failed, file exists!"
    exit 2
fi
if ! openssl genrsa -out $FILE $BITS 2> /dev/null; then
    echo "Failed!"
    exit 3
fi
echo "Done."

OPTIMIZER_KEY=$(openssl rsa -in $FILE -pubout 2> /dev/null | sha256sum | cut -c1-64)

cat << EOF

=== INSTRUCTIONS ================================================

1) Configure your Optimizer with the RSA key pair:

   $ configure
   # edit service anyfi optimizer <instance>
   # set rsa-key-pair file '${FILE}'
   # ...
   # commit
   # save
   # exit

2) Configure your CPE with the public optimizer key below, using
   its WEBUI, CLI or TR-069 interface (vendor extension
   InternetGatewayDevice.X_ANYFI_NET_Config.OptimizerKey).

=== OPTIMIZER KEY ===============================================

$OPTIMIZER_KEY

EOF

exit 0
